apiVersion: apps/v1
kind: Deployment
metadata:
  name: quiz-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quiz-app
  template:
    metadata:
      labels:
        app: quiz-app
    spec:
      containers:
      - name: quiz-app
        image: deenamanick/docker-quiz-app:latest
        ports:
        - containerPort: 5000
